package Exception

fun main(args: Array<String>) {

    val array = arrayOf("Hi", "Hi")

    println("Hello")
}